<?php /** @var \Perspective\Holiday\Block\Holiday $block */ ?>
<?php

$holiday = $block->getHoliday();
foreach ($holiday as $item) {
    $status = $item->getStatus();
    if ($status != 2) {
    $today = date("Y-m-d");
    $finish = $item->getFinish();
    $start = $item->getStart();?>
        <div style="text-align: center">
        <?php if ($start <= $today && $finish >= $today){?>
             <?php  echo $item->getText();
        }?>
        </div>
        </ br>
        <?php
}
}
